### ISSUE TITLE
Update version of json_api_client

### ISSUE THREAD

**Issue by JoshuaTatterton** [shiftcommerce/flex-ruby-gem#157]
At the time of writing this ticket we're currently using version `1.1.1` of the json_api_client gem and the latest version available is `1.5.3`. 

In the shift oms gem we're using the latest version 1.5.3, so this is clashing when trying to install both in the Flex Platform.

A branch already exists in the flex ruby gem upgrading the version [`update_json_api_client_gem`](https://github.com/shiftcommerce/flex-ruby-gem/tree/update_json_api_client_gem). This currently includes upgrading the json_api_client and updating the patches as needed (removing one as it has been merged and deployed)

The updated branch needs further testing on both the F/E ([`test/ruby_gem_with_update`](https://github.com/shiftcommerce/matalan-rails-site/tree/test/ruby_gem_with_update)) and the B/E ([`flex_ruby_gem_update_jsonapi_client`](https://github.com/shiftcommerce/flex-platform/tree/flex_ruby_gem_update_jsonapi_client)) at the branches provided. Once both tests suites pass then the gem can get released on both and the oms can be integrated properly into the admin panel.

**Comment by cbarratt** [comment]
^ I've created a branch/PR for `flex_deployment_client`, not entirely sure how's best to test this as I currently haven't yet handled a deployment.

**Comment by adamdullenty** [comment]
Closed by #158
